#!/bin/sh
sqlite3 oauth_token.db.empty ".read db.sql"
cd libs
./get-deps.sh
cd ..
echo =============================================================
echo "Please edit config.js.template and save as config.js"
echo "Please rename file oauth_token.db.empty to oauth_token.dn"
echo =============================================================
